export const CONTESTANTS = {
  DOCTOR: {
    name: "Doctor",
    health: 10,
    gender: "M",
    specialty: {
      type: "logic",

      power: 23,
      strength: 4,
      speed: 5,
      endurance: 4,
      dexterity: 5,
      balance: 5,

      logic: 37,
      memory: 9,
      puzzles: 7,
      fortitude: 9,
      awareness: 6,
      focus: 6,

      presence: 34,
      relationships: 5,
      likeability: 9,
      interrogation: 7,
      deception: 8,
      alliances: 5,
    },
    traits: {
      age: "60",
      status: "parent",
      trait: "hardworker",
    },
  },
  TRIATHLETE: {
    name: "Triathlete",
    health: 10,
    gender: "M",
    specialty: {
      type: "power",

      power: 44,
      strength: 7,
      speed: 9,
      endurance: 10,
      dexterity: 8,
      balance: 10,

      logic: 29,
      memory: 4,
      puzzles: 5,
      fortitude: 10,
      awareness: 3,
      focus: 7,

      presence: 18,
      relationships: 3,
      likeability: 3,
      interrogation: 3,
      deception: 4,
      alliances: 5,
    },
    traits: {
      age: "41",
      status: "parent",
      trait: "superfan",
    },
  },
  PHOTOGRAPHER: {
    name: "Photographer",
    health: 10,
    gender: "M",
    specialty: {
      type: "presence",

      power: 30,
      strength: 5,
      speed: 7,
      endurance: 5,
      dexterity: 8,
      balance: 5,

      logic: 23,
      memory: 6,
      puzzles: 7,
      fortitude: 2,
      awareness: 6,
      focus: 2,

      presence: 41,
      relationships: 8,
      likeability: 10,
      interrogation: 6,
      deception: 8,
      alliances: 9,
    },
    traits: {
      age: "35",
      status: "single",
      trait: "hard worker",
    },
  },
  HAIRDRESSER: {
    name: "Hairdresser",
    health: 10,
    gender: "M",
    specialty: {
      type: "presence",

      power: 24,
      strength: 4,
      speed: 5,
      endurance: 3,
      dexterity: 7,
      balance: 5,

      logic: 33,
      memory: 8,
      puzzles: 4,
      fortitude: 5,
      awareness: 5,
      focus: 9,

      presence: 43,
      relationships: 10,
      likeability: 8,
      interrogation: 10,
      deception: 7,
      alliances: 8,
    },
    traits: {
      age: 32,
      status: "single",
      trait: "Rebel",
    },
  },
  FIREMAN: {
    name: "Fireman",
    health: 10,
    gender: "M",
    specialty: {
      type: "power",

      power: 42,
      strength: 9,
      speed: 9,
      endurance: 9,
      dexterity: 8,
      balance: 7,

      logic: 25,
      memory: 4,
      puzzles: 3,
      fortitude: 9,
      awareness: 5,
      focus: 4,

      presence: 33,
      relationships: 9,
      likeability: 8,
      interrogation: 4,
      deception: 5,
      alliances: 7,
    },
    traits: {
      age: "33",
      status: "married",
      trait: "hardworker",
    },
  },
  FARMER: {
    name: "Farmer",
    health: 10,
    gender: "M",
    specialty: {
      type: "power",

      power: 41,
      strength: 8,
      speed: 8,
      endurance: 9,
      dexterity: 8,
      balance: 8,

      logic: 23,
      memory: 4,
      puzzles: 5,
      fortitude: 7,
      awareness: 3,
      focus: 4,

      presence: 36,
      relationships: 9,
      likeability: 9,
      interrogation: 6,
      deception: 5,
      alliances: 7,
    },
    traits: {
      age: "26",
      status: "married",
      trait: "loyal",
    },
  },
  MARINE: {
    name: "Marine",
    health: 10,
    gender: "M",
    specialty: {
      type: "power",

      power: 40,
      strength: 8,
      speed: 7,
      endurance: 8,
      dexterity: 9,
      balance: 8,

      logic: 26,
      memory: 2,
      puzzles: 2,
      fortitude: 8,
      awareness: 7,
      focus: 7,

      presence: 23,
      relationships: 4,
      likeability: 5,
      interrogation: 6,
      deception: 5,
      alliances: 3,
    },
    traits: {
      age: "61",
      status: "parent",
      trait: "lazy",
    },
  },
  ACCOUNTANT: {
    name: "Accountant",
    health: 10,
    gender: "M",
    specialty: {
      type: "logic",

      power: 23,
      strength: 5,
      speed: 6,
      endurance: 4,
      dexterity: 4,
      balance: 4,

      logic: 43,
      memory: 8,
      puzzles: 9,
      fortitude: 9,
      awareness: 8,
      focus: 9,

      presence: 34,
      relationships: 6,
      likeability: 5,
      interrogation: 6,
      deception: 8,
      alliances: 9,
    },
    traits: {
      age: "27",
      status: "married",
      trait: "lazy",
    },
  },
  VIDEO_GAMER: {
    name: "Video Gamer",
    health: 10,
    gender: "M",
    specialty: {
      type: "logic",

      power: 25,
      strength: 4,
      speed: 6,
      endurance: 4,
      dexterity: 6,
      balance: 5,

      logic: 45,
      memory: 9,
      puzzles: 10,
      fortitude: 7,
      awareness: 9,
      focus: 10,

      presence: 25,
      relationships: 4,
      likeability: 3,
      interrogation: 4,
      deception: 9,
      alliances: 5,
    },
    traits: {
      age: "21",
      status: "single",
      trait: "superfan",
    },
  },
  CONTRACTOR: {
    name: "Contractor",
    health: 10,
    gender: "M",
    specialty: {
      type: "power",

      power: 39,
      strength: 10,
      speed: 8,
      endurance: 6,
      dexterity: 9,
      balance: 6,

      logic: 22,
      memory: 4,
      puzzles: 3,
      fortitude: 8,
      awareness: 3,
      focus: 4,

      presence: 28,
      relationships: 7,
      likeability: 7,
      interrogation: 3,
      deception: 5,
      alliances: 6,

      swimming: 6,
    },
    traits: {
      age: "49",
      status: "parent",
      trait: "provider",
    },
  },
  STUDENT: {
    name: "Student",
    health: 10,
    gender: "M",
    specialty: {
      type: "presence",

      power: 31,
      strength: 5,
      speed: 7,
      endurance: 6,
      dexterity: 6,
      balance: 7,

      logic: 26,
      memory: 6,
      puzzles: 5,
      fortitude: 3,
      awareness: 3,
      focus: 9,

      presence: 39,
      relationships: 8,
      likeability: 10,
      interrogation: 5,
      deception: 6,
      alliances: 10,
    },
    traits: {
      age: "22",
      status: "single",
      trait: "loyal",
    },
  },
  POKER_PRO: {
    name: "Poker Pro",
    health: 10,
    gender: "M",
    specialty: {
      type: "presence",

      power: 24,
      strength: 4,
      speed: 3,
      endurance: 3,
      dexterity: 9,
      balance: 5,

      logic: 29,
      memory: 7,
      puzzles: 8,
      fortitude: 1,
      awareness: 7,
      focus: 6,

      presence: 41,
      relationships: 6,
      likeability: 6,
      interrogation: 10,
      deception: 10,
      alliances: 9,
    },
    traits: {
      age: "44",
      status: "married",
      trait: "superfan",
    },
  },
  ENTREPRENEUR: {
    name: "Entrepreneur",
    health: 10,
    gender: "M",
    specialty: {
      type: "logic",

      power: 32,
      strength: 7,
      speed: 7,
      endurance: 7,
      dexterity: 4,
      balance: 7,

      logic: 41,
      memory: 10,
      puzzles: 7,
      fortitude: 8,
      awareness: 7,
      focus: 9,

      presence: 22,
      relationships: 4,
      likeability: 5,
      interrogation: 5,
      deception: 4,
      alliances: 4,
    },
    traits: {
      age: "48",
      status: "parent",
      trait: "Rebel",
    },
  },
  YOGA_TEACHER: {
    name: "Yoga Teacher",
    health: 10,
    gender: "M",
    specialty: {
      type: "power",

      power: 41,
      strength: 8,
      speed: 6,
      endurance: 7,
      dexterity: 10,
      balance: 10,

      logic: 31,
      memory: 5,
      puzzles: 5,
      fortitude: 7,
      awareness: 8,
      focus: 6,

      presence: 23,
      relationships: 6,
      likeability: 7,
      interrogation: 2,
      deception: 2,
      alliances: 6,
    },
    traits: {
      age: "28",
      status: "single",
      trait: "Rebel",
    },
  },
  PSYCHIATRIST: {
    name: "Psychiatrist",
    health: 10,
    gender: "M",
    specialty: {
      type: "logic",

      power: 23,
      strength: 4,
      speed: 4,
      endurance: 3,
      dexterity: 6,
      balance: 6,

      logic: 40,
      memory: 7,
      puzzles: 8,
      fortitude: 8,
      awareness: 10,
      focus: 7,

      presence: 26,
      relationships: 6,
      likeability: 2,
      interrogation: 10,
      deception: 6,
      alliances: 2,
    },
    traits: {
      age: "41",
      status: "married",
      trait: "provider",
    },
  },
  INFLUENCER: {
    name: "Influencer",
    health: 10,
    gender: "M",
    specialty: {
      type: "presence",

      power: 20,
      strength: 4,
      speed: 3,
      endurance: 3,
      dexterity: 5,
      balance: 5,

      logic: 31,
      memory: 5,
      puzzles: 4,
      fortitude: 6,
      awareness: 10,
      focus: 6,

      presence: 40,
      relationships: 8,
      likeability: 8,
      interrogation: 9,
      deception: 7,
      alliances: 8,
    },
    traits: {
      age: "27",
      status: "single",
      trait: "lazy",
    },
  },
  CHEF: {
    name: "Chef",
    health: 10,
    gender: "M",
    specialty: {
      type: "presence",

      power: 27,
      strength: 6,
      speed: 3,
      endurance: 6,
      dexterity: 8,
      balance: 4,

      logic: 31,
      memory: 6,
      puzzles: 7,
      fortitude: 5,
      awareness: 6,
      focus: 7,

      presence: 42,
      relationships: 9,
      likeability: 9,
      interrogation: 7,
      deception: 9,
      alliances: 8,
    },
    traits: {
      age: "38",
      status: "married",
      trait: "provider",
    },
  },
  TEACHER: {
    name: "Teacher",
    health: 10,
    gender: "M",
    specialty: {
      type: "logic",

      power: 17,
      strength: 3,
      speed: 3,
      endurance: 2,
      dexterity: 5,
      balance: 4,

      logic: 40,
      memory: 8,
      puzzles: 8,
      fortitude: 10,
      awareness: 7,
      focus: 7,

      presence: 34,
      relationships: 8,
      likeability: 9,
      interrogation: 5,
      deception: 7,
      alliances: 5,
    },
    traits: {
      age: "51",
      status: "parent",
      trait: "loyal",
    },
  },
}

export const EVENT = [
  {
    name: "Double Down",
    text: "All players receive two Camp Life cards each.",
    action: "2 Camp Life cards to each player.",
  },
]
